---
title: "Activity Chapter 1"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

### Exercise 1

- Create a dataframe from the following vectors

```{r}
X <- c(1,2,3,1,4,5,2)
Y <- c(0,3,2,0,5,9,3)
Z <- c(1,1,1,1,1,1,1)
W <- c(5,4,3,2,1,0,4)

```

- Remove duplicates
- Name the resulting rows as "CA","SE","MA","BA","VA","SA"
- Create a new column T that is the sum of the first two divided by the first
- Change the X value of province BA by 2
- Select those provinces whose Y value is less than 4
- Create a factor that indicates whether the city is coastal or not (C or I) and add it as a column



### Exercise 2


- Load the dataset at the url http://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv indicating that the missing values are "?"

`url <-"http://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv"`.

If the url doesn't work, import the file from `forestfires.csv`.

- Make a SUMMARY of the dataframe.
- What is the dimension of the dataframe?
- Inspect the data, what class is each type? Extract the different values that the factors take.
- Indicates the proportion of missing values per column using sum and is.na and an apply (uses nrow).
- Edit the FFMC column taking it to the range 20 to 96.
- Gives an average of temperatures with respect to the days of the week and the months of the year.
- Returns the day of the week Monday, of the month of August with wind value between 3 and 6.


